version: 0.2

phases:
  install:
    runtime-versions:
      docker: 23
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com

      - echo "Setting up build variables"
      - REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:-latest}

      - echo Pulling latest image for layer caching...
      - docker pull $REPOSITORY_URI:latest || true

      - echo The commit hash is $COMMIT_HASH
      - echo The ECR Repository is $REPOSITORY_URI
      - echo The build environment is $BUILD_ENVIRONMENT
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...

      - |
        docker build \
          --cache-from=$REPOSITORY_URI:latest \
          -t $REPOSITORY_URI:$IMAGE_TAG \
          -t $REPOSITORY_URI:latest \
          -t $REPOSITORY_URI:latest-$BUILD_ENVIRONMENT .

      - echo Pushing Docker images...
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:latest-$BUILD_ENVIRONMENT

      - echo Preparing ECS task definition...
      - sed -i "s|\$account_id|$AWS_ACCOUNT_ID|g" ./.aws/task-definition.json
      - sed -i "s|\$aws_region|$AWS_DEFAULT_REGION|g" ./.aws/task-definition.json
      - sed -i "s|\$image_repo_name|$IMAGE_REPO_NAME|g" ./.aws/task-definition.json
      - sed -i "s|\$commit|$IMAGE_TAG|g" ./.aws/task-definition.json
      - sed -i "s|\$build_environment|$BUILD_ENVIRONMENT|g" ./.aws/task-definition.json
      - sed -i "s|\$ssm_prefix|$SSM_PREFIX|g" ./.aws/task-definition.json

      - echo Preparing imageDetail.json...
      - printf '{"ImageURI":"'"$REPOSITORY_URI:${IMAGE_TAG}"'"}' > ./.aws/imageDetail.json
      - cat ./.aws/imageDetail.json
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - ./.aws/appspec.yaml
    - ./.aws/imageDetail.json
    - ./.aws/task-definition.json
  discard-paths: yes
